kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  labels:
    k8s-app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: nginx
  template:
    metadata:
      name: nginx
      labels:
        k8s-app: nginx
    spec:
      containers:
        - name: nginx-app
          image: nginx
          imagePullPolicy: Always
      restartPolicy: Always
