kind: Service
apiVersion: v1
metadata:
  name: nginx
  labels:
    k8s-app: nginx
spec:
  ports:
    - name: tcp-9090-80
      protocol: TCP
      port: 9000
      targetPort: 80
  selector:
    k8s-app: nginx
  type: LoadBalancer
      