apiVersion: v1
kind: Pod
metadata:
  name: volume-test-pod
spec:
    restartPolicy: Never
    containers:
      - name: volume-test-container
        image: k8s.gcr.io/busybox
        command: [ "ls", "-la", "/data" ]
        volumeMounts:
          - mountPath: /data
            name: volume
    volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: auth-pv-claim
